### PR TITLE
Implement a debug drawer for Ogre 2.1

### PR DESCRIPTION
**Pull request by Ybalrid**
Hi!

Thanks for making btogre works with Ogre 2.1 for the physics part, it was really helpful for me!

I'm currently rewriting a debug drawer that works with 2.1, it's not really "finished" yet, but it's working already 
ss 2017-03-04 at 03 11 31

BtOgre's original debug drawer was just supporting displaying the edges, and only in white. Here you can choose to display the normals too for example, and the colors are representing their state in Bullet, like if a body is active or sleeping... (screenshot above)

There's 2 quirks for now : 

1) When using the HDR pipeline of Ogre, colors became some kind of relative "light values", and the final color is determined by a fragment shader (that implement a tone-mapping algorithm). Regular [0;1] colors stays black. I just hacked in a value that is multiplied with the color requested by Bullet

2) I need a pointer to the scene manager somewhere, so I have an access by string here, because n my engine, the main scene is "MAIN_SMGR". I just added a way to set this string to something else. I'm thinking about just passing the damn pointer on the DebugDrawer constructor.

Anyway, since you worked on making that thing works with the newer version of Ogre, but left out this part of the library, I'm sharing theses changes. I'm interested in any comment. It's currently just "prototype" level code right now and probably deserve some cleaning ^^"

If you want, you can go to the setting and activate the "issue" tracking on your repository. GitHub de-activate that by default for Forks. But it would make discussing this kind of things easier ^^"

Hopping your are interested! 😄

### CODE REVIEW

**Comment by Ybalrid** [comment]
Oh, and yeah, it's a bit "auto" heavy, so it will only be build-able on a C++11 compliant compiler. This shouldn't be an issue in 2017.

**Comment by nyxkn** [comment]
Hi! I'm glad you found this repository useful! I've always been meaning to get the debug drawer working but never got around to doing it, so your contribution is very welcome! And I'm fine with C++11 as my project uses it too. 
I've enabled the issue tracking as you suggested.

**Comment by Ybalrid** [comment]
Yeah, I've see this topic on the forums http://www.ogre3d.org/forums/viewtopic.php?f=25&t=83079&p=525583

There's one proposed by xrgo but I don't really like fact that this uses the frame listener, I'm more comfortable stepping it forward by hand so that I can do it at the same place than I step my physics.

I'm also planning to redo the way I handle these kind of little libraries in my game engine by using git submodules, right now I have the few files of btOgre randomply copied in one directory and compiled in, so It's not actually where I checkout my fork of this repo, so I was copy pasting code around... 

I don't know if you had the time to look at the code, but this solution just uses a manual object (when I was hacking around, I had several manual object, but it wasn't a good idea ^^")

This debug drawer uses the new ManualObject class. It's a bit different to the old one in the sense that you need to put index number to the vertices you give to it. The object is set to be described and drawn as a list of lines and don't cast shadows.

It will try to see if an unlit datablock exist, if it doesn't, it will create it and set the macrobloc to "no depth write" and "no culling"

Each step it will clear the manual object, and reconstruct the lines. 

I still need to do some cleanup on that code, so it's not ready to merge ^^"

**Comment by Ybalrid** [comment]
So, can you give this a try and tell me what you think of it?

You can pull directly from the Ogre21Clean branch here : https://github.com/Ybalrid/btogre/

It's supposed to be initialized this way : 

```c++
	//Don't mind .get(), it's just because it's a std::unique_ptr<> here
	debugDrawer = new BtOgre::DebugDrawer(rootNode, DynamicsWorld.get(), "ANN_MAIN_SMGR");
	DynamicsWorld->setDebugDrawer(debugDrawer);
	//Only if you are using HDR, set this to something high like 200 to 500
	debugDrawer->setUnlitDiffuseMultiplier(200);
```

You can actually set options on what you want it do draw : 

```c++
	debugDrawer->setDebugMode(btIDebugDraw::DebugDrawModes::DBG_DrawWireframe | btIDebugDraw::DebugDrawModes::DBG_FastWireframe | btIDebugDraw::DBG_DrawAabb | btIDebugDraw::DBG_DrawContactPoints);
```

The rest is as it has ever been using BtOgre ^^"

**Pull request closed without merging**
